name: mason_sampler
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  go_router: ^15.2.3 
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  fpdart: ^1.1.1
  material_design_icons_flutter: ^7.0.7296
  flutter_hooks: ^0.21.2
  theme_provider: ^0.6.0
  responsive_builder: ^0.7.1
  nanoid: ^1.0.0
  slang: ^4.7.2
  flutter_localizations:
    sdk: flutter
  window_manager: ^0.5.0
  slang_flutter: ^4.7.0
  pocketbase: ^0.23.0
  intl: ^0.20.2
  flutter_form_builder: ^10.0.1
  file_picker: ^10.1.9
  form_builder_file_picker: ^5.0.0
  form_builder_extra_fields: ^12.0.0
  cached_network_image: ^3.4.1
  material_table_view: ^5.4.0
  flutter_secure_storage: ^9.2.4
  universal_io: ^2.2.2
  flutter_side_menu: ^0.5.41

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  go_router_builder: ^3.0.1
  riverpod_builder: ^0.2.1
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.5.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  analyzer: ^7.4.5
  analyzer_plugin: ^0.13.1
  slang_build_runner: ^4.7.0
  flutter_launcher_icons: ^0.14.3
  flutter_gen_runner: ^5.10.0
  change_app_package_name: ^1.5.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    
flutter_gen:
  output: lib/src/core/assets/
  line_length: 80